### PR TITLE
7z.hexpat

### PR DESCRIPTION
**Pull request by jfsbrito**
# ImHex Custom Pattern: 7zip File Analysis

This repository contains a custom pattern for the ImHex tool that enables the analysis of 7zip files. The pattern allows for a structured view of 7zip files within ImHex, providing insights into various aspects of the file structure.

## Features

- Identification of 7zip files: The custom pattern detects and identifies 7zip file types based on their signature.
- Extraction of key information: The pattern extracts important details from the 7zip file, such as the format version, CRC values, relative offset of the end header, and file size.
- Differentiation of compression methods: The pattern distinguishes between LZMA and LZMA2 compression methods used within the 7zip file.
- Visualization of start and end headers: The pattern helps in visualizing the start and end headers of the 7zip file, making it easier to navigate through its structure.

## Usage

To use the custom pattern for analyzing 7zip files in ImHex, follow these steps:

1. Install ImHex: Ensure that you have ImHex installed on your system.
2. Open a 7zip file: Launch ImHex and open the 7zip file you want to analyze.
3. Apply the custom pattern: In the "Pattern" menu, select the custom pattern for 7zip file analysis and apply it.
4. Explore the file structure: ImHex will display the matched patterns, allowing you to explore the structure of the 7zip file with the extracted information.

Please note that this custom pattern is designed specifically for 7zip files and may not be suitable for other file formats.

## Contribution

Contributions to this custom pattern for 7zip file analysis are welcome. If you have any improvements, bug fixes, or suggestions, feel free to submit a pull request.

## License

This custom pattern for ImHex is licensed under the [MIT License](LICENSE.md). You are free to modify and distribute this pattern as per the terms of the license.

## Acknowledgments

We would like to acknowledge the developers of ImHex for providing an excellent tool for binary file analysis. The custom pattern for 7zip file analysis in this repository builds upon the capabilities of ImHex to enhance the understanding of 7zip file structures.

---

We hope you find this custom pattern useful for analyzing 7zip files using ImHex. If you encounter any issues or have any questions, please feel free to raise them in the "Issues" section of this repository.

Thanks!

### CODE REVIEW

**Comment by WerWolv** [comment]
Hi! Thanks a lot for your work!
Could you please also add the Pattern file to the table in our Readme and if possible upload a small example file to `/tests/patterns/test_data` named `7z.hexpat.7z`? That way the repo can automatically run unit tests on your pattern :)

**Comment by jfsbrito** [comment]
Hi! You're welcome, and thank you for your appreciation!

I'll be glad to help you with that. I'll add the Pattern file to the table in your Readme, and I'll also upload a small example file named "7z.hexpat.7z" to the "/tests/patterns/test_data" directory. This will allow the repository to automatically run unit tests on your pattern.

**Comment by WerWolv** [comment]
Thanks! Could you merge all your changes into this PR instead of opening one per file change? Also I think something went wrong with #130, that PR makes no changes at all

**Comment by jfsbrito** [comment]
@WerWolv , thanks! :)

**Pull request merged**
