### PR TITLE
Added pattern file for M.A.X. v1.04 game files.

### PR DESCRIPTION
**Pull request by nickntg**
This is a pattern file that can be used to read Mechanized Assault & Exploration game files. It is not my work - it is part of the excellent [M.A.X. port](https://github.com/klei1984/max) project.

### CODE REVIEW

**Comment by WerWolv** [comment]
Thanks a lot!
Are you one of the maintainers of that project? I'm happy to have the pattern added to our database but I also want to make sure that the original author of the file is okay with it.

**Comment by nickntg** [comment]
No, I am not. I am just a happy user and the pattern provided helped me out a lot.

**Comment by WerWolv** [comment]
Okay. Could you ping the original author / project maintainer then please? Just so everyone involed is okay with the submission.

**Comment by nickntg** [comment]
I did, the original author concurs (https://github.com/klei1984/max/discussions/25).

**Comment by WerWolv** [comment]
Awesome thank you!

**Comment by WerWolv** [comment]
Could you also add the new pattern to the list in the readme and possibly upload a test file (provided it's pretty small and copyright-free) to the `/tests/patterns/test_data` folder? That way unit tests are automatically being run on it

**Comment by nickntg** [comment]
Will do. Can I also sort the hex patterns list according to Name because my OCD kicked-in when I saw it?

**Comment by WerWolv** [comment]
It probably won't stay sorted for a long time and it will be replaced with a better system eventually but feel free

**Comment by nickntg** [comment]
@WerWolv Pushed.

**Pull request merged**
