### PR TITLE
Patterns/GBA Header

### PR DESCRIPTION
**Pull request by GekySan**
Hello, this PR adds:

- Game Boy Advance (GBA) hexpat.

No test files could be included due to copyright.

### CODE REVIEW

**Comment by Lemon4ksan** [comment]
There's a typo in line 139 'return _Unknown Licensee";_

**Comment by GekySan** [comment]
> There's a typo in line 139 'return _Unknown Licensee";_

Hello, I don’t see any typo errors. Could you clarify where it is, please ?

**Comment by paxcut** [comment]
I am pretty sure Lemon4san means `Licensee` which in this case is not a typo, but what else could it  be, `return`? `unknown`?  I don't think so. 

Among other meaning, a licensee is a person or group who is in possession of a license.

**Comment by GekySan** [comment]
> I am pretty sure Lemon4san means `Licensee` which in this case is not a typo, but what else could it be, `return`? `unknown`? I don't think so.
> 
> Among other meaning, a licensee is a person or group who is in possession of a license.

Ah, but I think `Licensee` is correct, and anyway, as mentioned in the comment in the code, I copied what [WerWolv did in Game Boy](https://github.com/WerWolv/ImHex-Patterns/blob/b9f5f1668bff1651189c5cefd9cf1bbc355a50a5/patterns/gb.hexpat#L230).

**Comment by paxcut** [comment]
I wasn't clear enough and for that I am sorry. My comment was meant to indicate that the above mentioned post incorrectly classified `Licensee` as a typo. That's an understandable mistake if English is not your mother tongue.

I added  the definition for the benefit of those who doubt it is the correct spelling.

**Comment by Lemon4ksan** [comment]
Sorry, my bad

**Comment by WerWolv** [comment]
Thank you!

**Pull request merged**
