### PR TITLE
Added: BZip3 File Header Pattern

### PR DESCRIPTION
**Pull request by Sewer56**
This adds parsing of BZip3 as a pattern for ImHex [documented here](https://github.com/kspalaiologos/bzip3/tree/master/doc)

image

I started using ImHex... 2-3 hours ago; so please let me know if I'm missing anything. 🤞

### CODE REVIEW

**Comment by Sewer56** [comment]
Note per PR:

- https://github.com/kspalaiologos/bzip3/pull/141#issuecomment-2537816794

This is the file format, not the frame format. Both formats have the same magic header; which may cause someone to confuse one for the other. (I certainly did)

**Comment by WerWolv** [comment]
Thanks a lot! Pattern looks good to me, however you should use `import std.mem;` nowadays instead of ´#include`

**Comment by Sewer56** [comment]
a-ok, done :clap:

**Comment by WerWolv** [comment]
Thank you!

**Pull request merged**
