### PR TITLE
Create tiff.hexpat

### PR DESCRIPTION
**Pull request by jacksonbarreto**
This pull request adds the pattern for TIFF file type support in ImHex.

In collaboration with my friend, we created the necessary pattern for identifying and parsing TIFF files in ImHex. With the addition of this pattern, ImHex will be able to recognize and process TIFF files properly.

This contribution extends the functionality of ImHex, allowing users to analyze and examine TIFF files efficiently. The implementation includes the accurate detection of TIFF format-specific headers and data structures according to the TIFF 6.0 specification.

We appreciate the opportunity to contribute to the project and hope that this addition will be useful to the ImHex community.

Please review the proposed changes and consider including them in the main repository.

Thank you!

### CODE REVIEW

**Comment by WerWolv** [comment]
Fantastic work, thank you! 
Please also add your pattern to the table in the README.md file and, if possible, add a small (< 100kB) test file to `/tests/patterns/test_data` called `tiff.hexpat.tiff` so the Unit tests can automatically be run on it.

**Comment by WerWolv** [comment]
Thank you!

**Comment by joelalves** [comment]
@WerWolv  We have a question about job. 
 the job pass 1 of 2 steps and fail on step Unit test. 
 it's normal these step fail? It's possible see the logs or fix these problem?

**Comment by WerWolv** [comment]
I checked the logs and it had nothing to do with your changes. It's failing to upload coverage information for some weird reason 
image

This happened on another repo of mine as well so it's probably an issue with the action I'm using for it

**Comment by joelalves** [comment]
okay. Thanks for you explanation.

In the next months,  i and my friend @jacksonbarreto  we will create another pattern.

**Pull request merged**
